### ISSUE TITLE
Missing Classes and Segmentation Fault During Rollout Execution

### ISSUE THREAD

**Issue by varad-more** [fishbotics/avoid-everything#4]
Hi, first of all thank you so much for the contributions and making the work open its very helpful.

I’m encountering some issues while working with the repository. It seems that a few required classes might be missing from the current version of the codebase, i.e. PretrainingMotionPolicyNetwork class. Additionally, I'm experiencing a segmentation fault when attempting to run the run_validation_rollouts.py file. Could you verify if all essential files/classes are included in the repo? 

Any advice on resolving the segmentation fault would also be greatly appreciated!

Thanks!

**Comment by fishbotics** [comment]
Hi @varad-more! Thanks for the feedback. This is totally my bad--tried rewriting the code to be more readable and ended up misnaming a few things. I fixed the import error (the class is called `PretrainingMotionPolicyTransformer` in pretraining.py and I had misnamed it in rope.py).

Can you paste the stack trace to the segfault? I will take a look.

**Comment by varad-more** [comment]
Hi @fishbotics Apologies for late reply, I was traveling.
Thank you for updating the code. Unfortunately, it's still not working on my end, and I'm now encountering a different error.
Here's the stack trace for your reference:

 
```
Traceback (most recent call last):
  File "/root/avoid-everything/avoid_everything/run_validation_rollouts.py", line 63, in <module>
    run(args.cfg_path)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/avoid-everything/avoid_everything/run_validation_rollouts.py", line 36, in run
    mdl = mdl_class.load_from_checkpoint(
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/core/module.py", line 1532, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/core/saving.py", line 90, in _load_from_checkpoint
    return _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/core/saving.py", line 136, in _load_state
    obj = cls(**_cls_kwargs)
  File "/root/avoid-everything/avoid_everything/pretraining.py", line 54, in __init__
    self.mpiformer = MotionPolicyTransformer(num_robot_points=num_robot_points)
  File "/root/avoid-everything/avoid_everything/mpiformer.py", line 172, in __init__
    self.point_cloud_embedder = MPiFormerPointNet(
  File "/root/avoid-everything/avoid_everything/mpiformer.py", line 103, in __init__
    self.sa1_module = SAModule(
TypeError: SAModule.__init__() got an unexpected keyword argument 'nn'
```

Regrading the segfault issue, there’s no stack trace provided, the script simply exits with the following message as soon as execution begins:
```
python3 data_generation.py --pool-size 1
Segmentation fault (core dumped)```


Please let me know if I need to change or update anything on my end to make it work. JFYI, I'm using the docker container build from specification provided in the repo.

**Comment by fishbotics** [comment]
I fixed the nn error. I'm not sure about the segfault error but will post if I have an update. Sorry about the bugs--I really appreciate your help in making the codebase easier to use!
